sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  # - "3.7"
cache:
  pip: true

env:
  - SKLEARN_VERSION=0.17.1
  - SKLEARN_VERSION=0.18.2
  - SKLEARN_VERSION=0.19.2
  - SKLEARN_VERSION=0.20.0

install:
  - pip install --only-binary=numpy,scipy
  - pip install -r requirements.txt
  - pip install scikit-learn=$SKLEARN_VERSION
  - pip install pytest mock pylint
  - python setup.py clean --all
  - pip install -e .[ensemble]
script:
  - PYTHONPATH=. python -m pytest -rw -v test
  - ./lint
